---
title: "Low prevalence of a priori power analyses in motor behavior research"
type: "article"
author: "McKay B., Corson A., Vinh M., Jeyarajan G., Tandon C., Brooks H., Hubley J., & Carter MJ."
year: "2023"
publication: "Journal of Motor Learning and Development"
pdf: ""
doi: "https://doi.org/10.1123/jmld.2022-0042"
github: "https://github.com/cartermaclab/proj_power-motor-behaviour"
materials: "https://osf.io/wsdpv/"
#supplementary: ""
preprint: "https://doi.org/10.51224/SRXIV.175"
toc: false
---

## Citation

### APA 7th

> McKay, B., Corson, A., Vinh, M.-A., Jeyarajan, G., Tandon, C., Brooks, H., Hubley, J., & Carter, M. J. (2023). Low prevalence of a priori power analyses in motor behavior research. *Journal of Motor Learning and Development*, 11(1), 15–28. https://doi.org/10.1123/jmld.2022-0042

### Bibtex

<pre>
@article{,
  title = {Low Prevalence of a Priori Power Analyses in Motor Behavior Research},
  author = {McKay, Brad and Corson, Abbey and Vinh, Mary-Anne and Jeyarajan, Gianna and Tandon, Chitrini and Brooks, Hugh and Hubley, Julie and Carter, Michael J.},
  year = {2023},
  date = {2022-12-26},
  journaltitle = {Journal of Motor Learning and Development},
  volume = {11},
  number = {1},
  pages = {15--28},
  publisher = {{Human Kinetics}},
  issn = {2325-3193, 2325-3215},
  doi = {10.1123/jmld.2022-0042},
  url = {https://journals.humankinetics.com/view/journals/jmld/11/1/article-p15.xml},
  urldate = {2023-07-13},
  langid = {english}
}
</pre>

## Abstract

A priori power analyses can ensure studies are unlikely to miss interesting effects. Recent metascience has suggested that kinesiology research may be underpowered and selectively reported. Here, we examined whether power analyses are being used to ensure informative studies in motor behavior. We reviewed every article published in three motor behavior journals between January 2019 and June 2021. Power analyses were reported in 13% of studies (*k* = 636) that tested a hypothesis. No study targeted the smallest effect size of interest. Most studies with a power analysis relied on estimates from previous experiments, pilot studies, or benchmarks to determine the effect size of interest. Studies without a power analysis reported support for their main hypothesis 85% of the time, while studies with a power analysis found support 76% of the time. The median sample sizes were *n* = 17.5 without a power analysis and *n* = 16 with a power analysis, suggesting the typical study design was underpowered for all but the largest plausible effect size. At present, power analyses are not being used to optimize the informativeness of motor behavior research. Adoption of this widely recommended practice may greatly enhance the credibility of the motor behavior literature.
