project:
  type: website
  #output-dir: _site

website:
  title: "carterlab"
  site-url: https://cartermaclab.org
  #reader-mode: true
  search: false
  page-footer:
    border: false
    left: "This site is permantly under construction."
    right: "Copyright 2023 &copy; Michael J. Carter"
  navbar:
    logo: images/lab-logo_right-black-text.png
    title: false
    right:
      - text: Home
        href: index.qmd
      - text: News
        href: news.qmd
      - text: People
        href: team.qmd
      - text: Research
        href: research.qmd
      - text: Papers
        href: papers.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Join
        href: join.qmd
      - text: Lab manual
        href: https://cartermaclab.github.io/lab-manual/
      - icon: github
        href: https://github.com/cartermaclab
        target: "_blank"
        aria-label: cartermaclab github
      - icon: instagram
        href: https://instagram.com/carterlab
        target: "_blank"
        aria-label: carterlab instagram

format:
  html:
    theme: [spacelab, theme.scss]
    fontsize: 1.15em
    css: styles.css
    toc: true



