---
title: ""
pagetitle: "CarterLab | Join"
toc: false
---

We are always seeking curious, creative, and self-motivated students to enhance our research team and learning environment. The Action, Cognition, & Metascience lab at McMaster University is committed to the training and development of all its team members by promoting a highly collaborative research and training environment, and fostering a passion for lifelong learning and discovery. We are committed to supporting and promoting diversity and equity in our lab. **Everyone---regardless of race, nationality, sex, gender, sexual orientation, age, disability, or religion---is welcome in our lab.**

## Undergraduate student opportunities

Undergraduate students are vital to the lab’s success and we love working with students from different academic programs and backgrounds. Undergraduate students will have the opportunity to work in the lab as part of their undergraduate degree requirements (e.g., research practicums, honour’s thesis, etc) or to explore an interest in sensorimotor neuroscience by gaining experience as a volunteer research assistant. You will have the opportunity to contribute to all stages of the research process, with the goal of disseminating your findings at an academic conference and/or in a peer-reviewed journal. There is also the possibility of paid summer positions depending on your experience and the availability of funds; however, these positions are generally given to students who have already worked in the lab. General inquiries regarding undergraduate opportunities in the lab such as volunteer positions, NSERC USRA, Kinesiology Summer Research Award, MIRA Summer Research Fellowship, etc. can be sent to cartem11 [at] mcmaster [dot] ca.

<!--
<font color="#d08770">**The application period for practicum / project and thesis positions in the lab for the 2025-26 academic year is now closed.**</font>
-->

<font color="#d08770">**The application period is now open for students interested in practicum / project and thesis positions in the lab for the 2026-27 academic year.**</font>


- Applications will be received until February 27 2026.
- Applicants selected for an interview will be notified by March 6 2026.
- Interviews will take place the week of March 16 to 20 2026.
- Offers for a position in the lab will be sent to selected students by March 31 2025.

Details about the undergraduate positions and expectations can be found in the [lab manual](https://cartermaclab.github.io/lab-manual/). If you are interested in joining the team, please complete the [online application form](https://forms.cloud.microsoft/r/iH9LVas493).


## Graduate student opportunities

The study of sensorimotor behaviour is multidisciplinary so students with backgrounds in the areas of, but not limited to, kinesiology, neuroscience, psychology, life or health sciences, engineering, or computer science are encouraged to apply. There are a limited number of graduate student positions in the lab at any given time. This approach allows for a more individualized training environment for each student, larger research stipends/bursaries, and the option to attend 1-2 academic conferences each year. Students interested in completing their M.Sc or Ph.D studies in the lab are encouraged to consult the relevant information pertaining to graduate studies in the [Department of Kinesiology](https://www.science.mcmaster.ca/kinesiology/graduate/graduate-studies.html){target="_blank"} and the [School of Graduate Studies](https://gs.mcmaster.ca/){target="_blank"}.

### M.Sc and Ph.D applicants

If you are interested in completing your M.Sc or Ph.D in the lab, please send 1) an up-to-date curriculum vitae, 2) unofficial academic transcripts, and 3) a 1-page statement of research interests to cartem11 [at] mcmaster [dot] ca.
