---
title: "Past Lab News"
pagetitle: "CarterLab | News"
toc: false
---

<font color="#d08770">[May 14 2024].</font> **Paper accepted**. Sullivan SR, Lokesh R, Peters CS, Calalo J, Roth AR, Buggeln JH, Ngo TT, Carter MJ, &
Cashaback JGA. (Accepted). Indecision under time pressure arises from suboptimal switching behaviour. *Journal of Neurophysiology*.

<font color="#d08770">[March 03 2025].</font> **New Preprint**. Lalli, M., Al Afif, N., Tang, J., Hasan, H., Dissanayake, E., Sussman, V., Lokesh, R., Rathwell, S., Cashaback, J.G.A., & Carter, M.J. Preferences for costly cooperation are highly individualized. *PsyAr$\chi$iv*. [https://doi.org/10.31234/osf.io/3qaeu_v3](https://doi.org/10.31234/osf.io/3qaeu_v3){target="_blank"}

<font color="#d08770">[January 20 2025].</font> **Announcement**. The application period is now open for students interested in a practicum, project, thesis, or volunteer position in the lab for the 2025-26 academic year. Please see [https://cartermaclab.org/join](https://cartermaclab.org/join) for details.

<font color="#d08770">[October 21 2024].</font> **New milestone**. Congratulations to Nour Al Afif on successfully defending her MSc work. We are excited that Nour is staying in the lab for her doctoral studies.

<font color="#d08770">[September 18 2024].</font> **Paper accepted**. Roth, A.M., Buggeln, J.H., Hoh, J., Woods, J.M., Sullivan, S.R., Ngo, T., Calalo, J.A., Lokesh, R., Morton, S.M., Grill, S., Jeka, J.J., Carter, M.J., & Cashaback, J.G.A. Roles and interplay of reinforcement-based and error-based processes during reaching and gait in neurotypical adults and individuals with Parkinson's disease. *PLoS Computational Biology*.

<font color="#d08770">[September 05 2024].</font> **New milestone**. Congratulations to Mikayla Lalli on successfully defending her MSc work. We are excited that Mikayla is staying in the lab for her doctoral studies.

<font color="#d08770">[September 03 2024].</font> **Paper accepted**. St. Germain, L., McKay, B., Barbera, L., Tandon, C., Seedu, J., Carrillo, C., Brown, B.M.Y., & Carter, M.J. Autonomy-supportive instructional language does not enhance skill acquisition compared to controlling instructional language. *Psychological Research*.

<font color="#d08770">[August 20 2024].</font> **New Preprint**. Calalo, J.A., Ngo, T.T., Sullivan, S.R., Strand, K., Buggeln, J.H., Lokesh, R., Roth, A.M., Carter, M.J, Kurtzer, I.L., & Cashaback, J.G.A. Online movements reflect ongoing deliberation. *bioR$\chi$iv*. [https://doi.org/10.1101/2024.08.19.608669](https://doi.org/10.1101/2024.08.19.608669){target="_blank"}

<font color="#d08770">[April 12 2024].</font> **Paper accepted**. McKay, B., Corson, A.E., Seedu, J., De Faveri, C.S., Hasan, H., Arnold, K., Adams, F.C., & Carter, M.J. Reporting bias, not external focus: A robust Bayesian meta-analysis and systematic review of the attentional focus literature. *Psychological Bulletin*.

<font color="#d08770">[January 22 2024].</font> **Paper accepted**. Roth, A.M., Lokesh, R., Tang, J., Buggeln, J.H., Smith, C., Calalo, J.A., Sullivan, S.R., Ngo, T., St. Germain, L., Carter, M.J., & Cashaback, J.G.A. Punishment leads to greater sensorimotor learning but less movement variability compared to reward. *Neuroscience*. [https://doi.org/10.1016/j.neuroscience.2024.01.004](https://doi.org/10.1016/j.neuroscience.2024.01.004){target="_blank"}

<font color="#d08770">[September 22 2023].</font> **New award**. Congratulations to Daniel Deletsu who was awarded a 2-year Master's scholarship from the Heart and Stroke Foundation of Canada, Brain Canada Foundation, and the Canadian Institutes of Health Research.

<font color="#d08770">[September 6 2023].</font> **Paper accepted**. Roth, A.M., Calalo, J.A., Lokesh, R., Sullivan, S.R., Grill, S., Jeka, J.J., van der Kooij, K., Carter, M.J, & Cashaback, J.G.A. Reinforcement-based processes actively regulate motor exploration along redundant solution manifolds. *Proceedings of the Royal Society B*. [https://doi.org/10.1098/rspb.2023.1475](https://doi.org/10.1098/rspb.2023.1475){target="_blank"}

<font color="#d08770">[August 28 2023].</font> **New members**. Welcome to Daniel Deletsu and Jiaqiao (Jack) Tang. Daniel will be starting his M.Sc in the lab and Jack will be starting his Ph.D in the lab.

<font color="#d08770">[June 28 2023].</font> **New milestone**. Congratulations Dr. Laura St. Germain on a successfully defending your doctoral work.

<font color="#d08770">[June 20 2023].</font> **New award**. Congratulations to Laura St. Germain (Ph.D. Candidate) on winning the 2023 Franklin Henry Young Scientist Award in Motor Control and Learning from the Canadian Society for Psychomotor Learning and Sport Psychology.

<font color="#d08770">[June 16 2023].</font> **New preprint**. McKay, B., Corson, A.E., Seedu, J., De Faveri, C.S., Hasan, H., Arnold, K., Adams, F.C., & Carter, M.J. Reporting bias, not external focus: A robust Bayesian meta-analysis of the attentional focus literature. *SportR*$\chi$*iv*. [https://doi.org/10.51224/SRXIV.304](https://doi.org/10.51224/SRXIV.304){target="_blank"}

<font color="#d08770">[May 26 2023].</font> **Paper accepted**. Lokesh, R., Sullivan, S.R., St. Germain, L., Roth, A.M., Calalo, J.A., Buggeln, J., Ngo, T., Marchhart, V.R.F., Carter, M.J, & Cashaback, J.G.A. Visual accuracy dominates over haptic speed for state estimation of a partner during collaborative sensorimotor interactions. *Journal of Neurophysiology*. [https://doi.org/10.1152/jn.00053.2023](https://doi.org/10.1152/jn.00053.2023){target="_blank"}

<font color="#d08770">[May 19 2023].</font> **New preprint**. St. Germain, L., McKay, B., Tandon, C., Seedu, J., Barbera, L., Carrillo, C., Brown, D.M.Y., & Carter, M.J. Autonomy-supportive instructional language does not enhance skill acquisition compared to controlling instructional language. *SportR*$\chi$*iv*. [https://doi.org/10.51224/SRXIV.298](https://doi.org/10.51224/SRXIV.298){target="_blank"}

<font color="#d08770">[April 13 2023].</font> **Paper accepted**. McKay, B., Bacelar, M.F.B., Parma, J.O., Miller, M.W., & Carter, M.J. The combination of reporting bias and underpowered study designs has substantially exaggerated the motor learning benefits of self-controlled practice and enhanced expectancies: A meta-analysis. *International Review of Sport and Exercise Psychology*. [https://doi.org/10.1080/1750984X.2023.2207255](https://doi.org/10.1080/1750984X.2023.2207255){target="_blank"}
