---
title: "Gaze behaviour reveals flexible encoding of competing reach goals under conditions of target uncertainty"
type: "article"
author: "de Brouwer AJ., Carter MJ., Smail LC., Wolpert DM., Gallivan JP., & Flanagan JR."
year: "2020"
publication: "bioR&#43859;iv"
pdf: ""
doi: "https://doi.org/10.1101/2020.09.02.279414"
github: ""
materials: ""
preprint: ""
toc: false
---

## Citation

### APA 7th

> Brouwer, A. J. de, Carter, M. J., Smail, L. C., Wolpert, D. M., Gallivan, J. P., & Flanagan, J. R. (2020). Gaze behaviour reveals flexible encoding of competing reach goals under conditions of target uncertainty. *bioRxiv*. https://doi.org/10.1101/2020.09.02.279414

### Bibtex

<pre>
@article{,
  title = {Gaze Behaviour Reveals Flexible Encoding of Competing Reach Goals under Conditions of Target Uncertainty},
  author = {{de Brouwer}, Anouk J., and Carter, Michael J. and Smail, Lauren C. and Wolpert, Daniel M. and Gallivan, Jason P. and Flanagan, J. Randall},
  date = {2020-09-03},
  eprinttype = {bioRxiv},
  eprintclass = {New Results},
  pages = {2020.09.02.279414},
  doi = {10.1101/2020.09.02.279414},
  url = {https://www.biorxiv.org/content/10.1101/2020.09.02.279414v1},
  urldate = {2023-07-13},
  langid = {english},
  pubstate = {preprint}
}
</pre>

## Abstract

In daily tasks, we are often confronted with competing potential targets and must select one to act on. It has been suggested that, prior to target selection, the human brain encodes the motor goals of multiple, potential targets. However, this view remains controversial and it has been argued that only a single motor goal is encoded, or that motor goals are only specified after target selection. To investigate this issue, we measured participants’ gaze behaviour while viewing two potential reach targets, one of which was cued after a preview period. We applied visuomotor rotations to dissociate each visual target location from its corresponding motor goal location; i.e., the location participants needed to aim their hand toward to bring the rotated cursor to the target. During the preview period, participants most often fixated both motor goals but also frequently fixated one, or neither, motor goal location. Further gaze analysis revealed that on trials in which both motor goals were fixated, both locations were held in memory simultaneously. These findings show that, at the level of single trials, the brain most often encodes multiple motor goals prior to target selection, but may also encode either one or no motor goals. This result may help reconcile a key debate concerning the specification of motor goals in cases of target uncertainty.
