---
title: "Reporting bias, not external focus: A robust Bayesian meta-analysis of the attentional focus literature"
type: "article"
author: "McKay B., Corson AE., Seedu J., De Faveri, CS., Hasan, H., Arnold, K., Adams, FC., & Carter, MJ."
year: "2023"
publication: "SportR&#43859;iv"
pdf: ""
doi: "https://doi.org/10.51224/SRXIV.304"
github: "https://github.com/cartermaclab/proj_foa-optimal-theory"
materials: ""
preprint: ""
toc: false
---

## Citation

### APA 7th

> McKay, B., Corson, A., Seedu, J., Faveri, C. D., Hasan, H., Arnold, K., Adams, F., & Carter, M. (2023). Reporting bias, not external focus: A robust Bayesian meta-analysis of the attentional focus literature. *SportRxiv*. https://doi.org/10.51224/SRXIV.304

### Bibtex

<pre>
@article{,
  title = {Reporting Bias, Not External Focus: {{A}} Robust {{Bayesian}} Meta-Analysis of the Attentional Focus Literature},
  shorttitle = {Reporting Bias, Not External Focus},
  author = {McKay, Brad and Corson, Abbey and Seedu, Jeswende and Faveri, Celeste De and Hasan, Hibaa and Arnold, Kristen and Adams, Faith and Carter, Michael},
  date = {2023-06-20},
  eprinttype = {SportRxiv},
  doi = {10.51224/SRXIV.304},
  url = {https://sportrxiv.org/index.php/server/preprint/view/304},
  urldate = {2023-07-13},
  langid = {english},
  pubstate = {preprint},
  keywords = {Heterogeneity,Metascience,OPTIMAL theory,Skill acquisition,Sport science}
}
</pre>

## Abstract

Evidence has ostensibly been accumulating over the past two decades suggesting that an external focus of attention is superior to an internal focus for the performance and learning of motor skills. Seven previous meta-studies have all reported evidence of external focus superiority---the most comprehensive of which concluded the benefits apply to motor skill (a) retention, (b) transfer, and (c) performance; results in (d) reduced electromyographic activity during performance, and that (e) more distal external foci are superior to proximal external foci for performance. Here, we re-analyzed these data using robust Bayesian meta-analysis methods that included several plausible models of publication bias. We found moderate to strong evidence of publication bias for all five analyses. After correcting for publication bias, estimated mean effects were negligible: *g* = .01 (performance), *g* = .15 (retention), *g* = .09 (transfer), *g* = .06 (electromyography), and *g* = -.01 (distance effect). Bayes factors indicated data favored the null for each analysis, ranging from BF~01~ = 1.3 (retention) to 5.74 (performance). Further, we found clear evidence of heterogeneity in each analysis, suggesting the impact of attentional focus depends on yet unknown contextual factors. Our results contradict the existing consensus that an external focus is always more effective than an internal focus. Instead, focus of attention appears to have a variety of effects that we cannot account for, and on average those effects are small to nil. These results parallel previous metascience suggesting publication bias has obfuscated the motor learning literature.
