---
title: "Anodal transcranial direct current stimulation applied over the supplementary motor area delays spontaneous antiphase-to-in-phase transitions"
type: "article"
author: "Carter MJ., Maslovat D., & Carlsen AN."
year: "2015"
publication: "Journal of Neurophysiology"
pdf: ""
doi: "https://doi.org/10.1152/jn.00662.2014"
github: ""
materials: ""
#supplementary: ""
preprint: ""
toc: false
---

## Citation

### APA 7th

> Carter, M. J., Maslovat, D., & Carlsen, A. N. (2015). Anodal transcranial direct current stimulation applied over the supplementary motor area delays spontaneous antiphase-to-in-phase transitions. *Journal of Neurophysiology*, 113(3), 780–785. https://doi.org/10.1152/jn.00662.2014

### Bibtex

<pre>
@article{,
  title = {Anodal Transcranial Direct Current Stimulation Applied over the Supplementary Motor Area Delays Spontaneous Antiphase-to-in-Phase Transitions},
  author = {Carter, Michael J. and Maslovat, Dana and Carlsen, Anthony N.},
  date = {2015-02},
  journaltitle = {Journal of Neurophysiology},
  volume = {113},
  number = {3},
  pages = {780--785},
  publisher = {{American Physiological Society}},
  issn = {0022-3077},
  doi = {10.1152/jn.00662.2014},
  url = {https://journals.physiology.org/doi/full/10.1152/jn.00662.2014},
  urldate = {2023-07-13},
  keywords = {bimanual coordination,motor control,neurostimulation,phase transition}
}
</pre>

## Abstract

Coordinated bimanual oscillatory movements often involve one of two intrinsically stable phasing relationships characterized as in-phase (symmetrical) or antiphase (asymmetrical). The in-phase mode is typically more stable than antiphase, and if movement frequency is increasing during antiphase movements, a spontaneous transition to the in-phase pattern occurs. There is converging neurophysiological evidence that the supplementary motor area (SMA) plays a critical role in the successful performance of these patterns, especially during antiphase movements. We investigated whether modulating the excitability of the SMA via offline transcranial direct current stimulation (tDCS) would delay the onset of anti-to-in-phase transitions. Participants completed two sessions (separated by ∼48 h), each consisting of a pre- and post-tDCS block in which they performed metronome-paced trials of rhythmic in- and antiphase bimanual supination-pronation movements as target oscillation frequency was systematically increased. Anodal or cathodal tDCS was applied over the SMA between the pre- and post-tDCS blocks in each session. Following anodal tDCS, participants performed the antiphase pattern with increased accuracy and stability and were able to maintain the coordination pattern at a higher oscillation frequency. Antiphase performance was unchanged following cathodal tDCS, and neither tDCS polarity affected the in-phase mode. Our findings suggest increased SMA excitability induced by anodal tDCS can improve antiphase performance and adds to the accumulating evidence of the pivotal role of the SMA in interlimb coordination.
