---
title: "Judgments of learning are significantly higher following feedback on relatively good versus relatively poor trials despite no actual learning differences"
type: "article"
author: "Carter MJ."
year: "2016"
publication: "Human Movement Science"
pdf: ""
doi: "https://doi.org/10.1016/j.humov.2015.11.006"
github: ""
materials: ""
#supplementary: ""
preprint: ""
toc: false
---

## Citation

### APA 7th

> Carter, M. J., Smith, V., & Ste-Marie, D. M. (2016). Judgments of learning are significantly higher following feedback on relatively good versus relatively poor trials despite no actual learning differences. *Human Movement Science*, 45, 63–70. https://doi.org/10.1016/j.humov.2015.11.006

### Bibtex

<pre>
@article{,
  title = {Judgments of Learning Are Significantly Higher Following Feedback on Relatively Good versus Relatively Poor Trials despite No Actual Learning Differences},
  author = {Carter, Michael J. and Smith, Victoria and Ste-Marie, Diane M.},
  date = {2016-02-01},
  journaltitle = {Human Movement Science},
  shortjournal = {Human Movement Science},
  volume = {45},
  pages = {63--70},
  issn = {0167-9457},
  doi = {10.1016/j.humov.2015.11.006},
  url = {https://www.sciencedirect.com/science/article/pii/S0167945715300567},
  urldate = {2023-07-13},
  langid = {english},
  keywords = {Knowledge of results,Metacognition,Motor learning,Skill acquisition}
}
</pre>

## Abstract

Studies have consistently shown that prospective metacognitive judgments of learning are often inaccurate because humans mistakenly interpret current performance levels as valid indices of learning. These metacognitive discrepancies are strongly related to conditions of practice. Here, we examined how the type of feedback (after good versus poor trials) received during practice and awareness (aware versus unaware) of this manipulation affected judgments of learning and actual learning. After each six-trial block, participants received feedback on their three best trials or three worst trials and half of the participants were made explicitly aware of the type of feedback they received while the other half were unaware. Judgments of learning were made at the end of each six-trial block and before the 24-h retention test. Results indicated no motor performance differences between groups in practice or retention; however, receiving feedback on relatively good compared to relatively poor trials resulted in significantly higher judgments of learning in practice and retention, irrespective of awareness. These results suggest that KR on relatively good versus relatively poor trials can have dissociable effects on judgments of learning in the absence of actual learning differences, even when participants are made aware of their feedback manipulation.
