---
title: "Development and validation of the Movement Imagery Questionnaire for Children (MIQ-C)"
type: "article"
author: "Martini R., Carter MJ., Yoxon E., Cumming J., & Ste-Marie DM."
year: "2016"
publication: "Psychology of Sport and Exercise"
pdf: ""
doi: "https://doi.org/10.1016/j.psychsport.2015.08.008"
github: ""
materials: ""
#supplementary: ""
preprint: ""
toc: false
---

## Citation

### APA 7th

> Martini, R., Carter, M. J., Yoxon, E., Cumming, J., & Ste-Marie, D. M. (2016). Development and validation of the Movement Imagery Questionnaire for Children (MIQ-C). *Psychology of Sport and Exercise*, 22, 190–201. https://doi.org/10.1016/j.psychsport.2015.08.008

### Bibtex

<pre>
@article{,
  title = {Development and Validation of the {{Movement Imagery Questionnaire}} for {{Children}} ({{MIQ-C}})},
  author = {Martini, Rose and Carter, Michael J. and Yoxon, Emma and Cumming, Jennifer and Ste-Marie, Diane M.},
  date = {2016-01-01},
  journaltitle = {Psychology of Sport and Exercise},
  shortjournal = {Psychology of Sport and Exercise},
  volume = {22},
  pages = {190--201},
  issn = {1469-0292},
  doi = {10.1016/j.psychsport.2015.08.008},
  url = {https://www.sciencedirect.com/science/article/pii/S1469029215300054},
  urldate = {2023-07-13},
  langid = {english},
  keywords = {Ease of imaging,Imagery ability,Scale development}
}
</pre>

## Abstract

The ability to perform movement imagery has been shown to influence motor performance and learning in sports and rehabilitation. Self-report questionnaires have been developed to assess movement imagery ability in adults, such as the Movement Imagery Questionnaire 3 (MIQ-3); however, there is a dearth of developmentally appropriate measures for use with children. To address this gap, the focus of this research was to develop an imagery ability questionnaire for children. This process involved adaptation of the MIQ-3 via: i) cognitive interviewing with twenty children, ii) validation with 206 children by examining its factor structure via multitrait-multi method confirmatory factor analysis, and iii) examination of test-retest reliability with 23 children. The findings of Study 1 led to changes to the wording of the questionnaire and modifications of the instructions to successfully adapt the MIQ-3 for children aged 7–12 years. The validation undertaken in Study 2 found that a correlated-traits correlated-uniqueness model provided the best fit to the data. Finally, test-retest reliabilities varied from fair (for external visual imagery) to substantial (for kinesthetic imagery). With respect to ease of imaging, no significant gender or age-group differences were noted. However, significant difference were found among the three imagery modalities (*p* < .001), with external visual imagery rated as easiest to image and kinesthetic imagery rated as the most difficult. Taken together, findings support the use of the MIQ-C for examining movement imagery ability with children.
