---
title: "Motor skill retention is modulated by strategy choice during self-controlled knowledge of results schedules "
type: "article"
author: "Carter MJ., Rathwell S., & Ste-Marie DM."
year: "2016"
publication: "Journal of Motor Learning and Development"
pdf: ""
doi: "https://doi.org/10.1123/jmld.2015-0023"
github: ""
materials: ""
#supplementary: ""
preprint: ""
toc: false
---

## Citation

### APA 7th

> Carter, M., Rathwell, S., & Ste-Marie, D. (2016). Motor skill retention is modulated by strategy choice during self-controlled knowledge of results schedules. *Journal of Motor Learning and Development*, 4(1), 100–115. https://doi.org/10.1123/jmld.2015-0023

### Bibtex

<pre>
@article{,
  title = {Motor Skill Retention Is Modulated by Strategy Choice during Self-Controlled Knowledge of Results Schedules},
  author = {Carter, Michael and Rathwell, Scott and Ste-Marie, Diane},
  date = {2016-06-01},
  journaltitle = {Journal of Motor Learning and Development},
  volume = {4},
  number = {1},
  pages = {100--115},
  publisher = {{Human Kinetics, Inc.}},
  issn = {2325-3193, 2325-3215},
  doi = {10.1123/jmld.2015-0023},
  url = {https://journals.humankinetics.com/view/journals/jmld/4/1/article-p100.xml},
  urldate = {2023-07-13},
  langid = {american}
}
</pre>

## Abstract

Investigations into the strategies that are used by participants when they control their knowledge of results (KR) schedule during practice have predominantly relied on multiple-choice questionnaires. More recently, open-ended questions have been used to allow participants to produce their own descriptions rather than selecting a strategy from a predetermined list. This approach has in fact generated new information about the cognitive strategies used by learners to request KR during practice (e.g., Laughlin et al., 2015). Consequently, we examined strategy use in self-controlled KR learning situations using open-ended questions at two different time points during practice. An inductive thematic content analysis revealed five themes that represented participants’ unique strategies for requesting KR. This analysis identified two dominant KR strategies: “establish a baseline understanding” in the first half of practice and “confirm a perceived good trial” in the second half of practice. Both strategies were associated with superior retention compared with a yoked group, a group that was unable to engage in KR request strategies because KR was imposed rather than chosen. Our results indicate that the learning advantages of self-controlled KR schedules over yoked schedules may not only depend on what strategy is used, but also when it is used.
