---
title: "An interpolated activity during the knowledge-of-results delay interval eliminates the learning advantages of self-controlled feedback schedules"
type: "article"
author: "Carter MJ. & Ste-Marie DM."
year: "2017"
publication: "Psychological Research"
pdf: ""
doi: "https://doi.org/10.1007/s00426-016-0757-2"
github: ""
materials: ""
#supplementary: ""
preprint: ""
toc: false
---

## Citation

### APA 7th

> Carter, M. J., & Ste-Marie, D. M. (2017). An interpolated activity during the knowledge-of-results delay interval eliminates the learning advantages of self-controlled feedback schedules. *Psychological Research*, 81(2), 399–406. https://doi.org/10.1007/s00426-016-0757-2

### Bibtex

<pre>
@article{,
  title = {An Interpolated Activity during the Knowledge-of-Results Delay Interval Eliminates the Learning Advantages of Self-Controlled Feedback Schedules},
  author = {Carter, Michael J. and Ste-Marie, Diane M.},
  date = {2017-03-01},
  journaltitle = {Psychological Research},
  shortjournal = {Psychological Research},
  volume = {81},
  number = {2},
  pages = {399--406},
  issn = {1430-2772},
  doi = {10.1007/s00426-016-0757-2},
  url = {https://doi.org/10.1007/s00426-016-0757-2},
  urldate = {2023-07-13},
  langid = {english},
  keywords = {Interpolate Activity,Learning Benefit,Movement Completion,Performance Appraisal,Root Mean Square Error}
}
</pre>

## Abstract

The learning advantages of self-controlled knowledge-of-results (KR) schedules compared to yoked schedules have been linked to the optimization of the informational value of the KR received for the enhancement of one’s error-detection capabilities. This suggests that information-processing activities that occur after motor execution, but prior to receiving KR (i.e., the KR-delay interval) may underlie self-controlled KR learning advantages. The present experiment investigated whether self-controlled KR learning benefits would be eliminated if an interpolated activity was performed during the KR-delay interval. Participants practiced a waveform matching task that required two rapid elbow extension-flexion reversals in one of four groups using a factorial combination of choice (self-controlled, yoked) and KR-delay interval (empty, interpolated). The waveform had specific spatial and temporal constraints, and an overall movement time goal. The results indicated that the self-controlled + empty group had superior retention and transfer scores compared to all other groups. Moreover, the self-controlled + interpolated and yoked + interpolated groups did not differ significantly in retention and transfer; thus, the interpolated activity eliminated the typically found learning benefits of self-controlled KR. No significant differences were found between the two yoked groups. We suggest the interpolated activity interfered with information-processing activities specific to self-controlled KR conditions that occur during the KR-delay interval and that these activities are vital for reaping the associated learning benefits. These findings add to the growing evidence that challenge the motivational account of self-controlled KR learning advantages and instead highlights informational factors associated with the KR-delay interval as an important variable for motor learning under self-controlled KR schedules.
