---
title: "Response preparation and execution during intentional bimanual pattern switching"
type: "article"
author: "Maslovat D., Carter MJ., & Carlsen AN."
year: "2017"
publication: "Journal of Neurophysiology"
pdf: ""
doi: "https://doi.org/10.1152/jn.00323.2017"
github: ""
materials: ""
#supplementary: ""
preprint: ""
toc: false
---

## Citation

### APA 7th

> Maslovat, D., Carter, M. J., & Carlsen, A. N. (2017). Response preparation and execution during intentional bimanual pattern switching. *Journal of Neurophysiology*, 118(3), 1720–1731. https://doi.org/10.1152/jn.00323.2017

### Bibtex

<pre>
@article{,
  title = {Response Preparation and Execution during Intentional Bimanual Pattern Switching},
  author = {Maslovat, Dana and Carter, Michael J. and Carlsen, Anthony N.},
  date = {2017-09},
  journaltitle = {Journal of Neurophysiology},
  volume = {118},
  number = {3},
  pages = {1720--1731},
  publisher = {{American Physiological Society}},
  issn = {0022-3077},
  doi = {10.1152/jn.00323.2017},
  url = {https://journals.physiology.org/doi/full/10.1152/jn.00323.2017},
  urldate = {2023-07-13},
  keywords = {coordination dynamics,intentional switching,preparation,startle,transitions}
}
</pre>

## Abstract

During continuous bimanual coordination, in-phase (IP; 0° relative phase) and anti-phase (AP; 180° relative phase) patterns can be stably performed without practice. Paradigms in which participants are required to intentionally switch between these coordination patterns have been used to investigate the interaction between the performer’s intentions and intrinsic dynamics of the body’s preferred patterns. The current study examined the processes associated with switching preparation and execution through the use of a startling acoustic stimulus (SAS) as the switch stimulus. A SAS is known to involuntarily trigger preprogrammed responses at a shortened latency and, thus, can be used to probe advance preparation. Participants performed cyclical IP and AP bimanual elbow extension-flexion movements in which they were required to switch patterns in response to an auditory switch cue, which was either nonstartling (80 dB) or a SAS (120 dB). Results indicated that reaction time to the switch stimulus (i.e., switch onset) was significantly reduced on startle trials, indicative of advance preparation of the switch response. Similarly, switching time was reduced on startle trials, which was attributed to increased neural activation caused by the SAS. Switching time was also shorter for AP to IP trials, but only when the switching stimulus occurred at either the midpoint or reversal locations within the movement cycle, suggesting that the switch location may affect the intrinsic dynamics of the system.
