---
title: "Increased perceptions of autonomy through choice fail to enhance motor skill retention"
type: "article"
author: "St. Germain L., Williams A., Balbaa N., Poskus A., Leshchyshen O., Lohse KR., & Carter MJ."
year: "2022"
publication: "Journal of Experimental Psychology: Human Perception and Performance"
pdf: ""
doi: "https://doi.org/10.1037/xhp0000992"
github: "https://github.com/cartermaclab/expt_explicit-yoked"
materials: ""
#supplementary: ""
preprint: "https://psyarxiv.com/s34fg/"
toc: false
---

## Citation

### APA 7th

> St. Germain, L., Williams, A., Balbaa, N., Poskus, A., Leshchyshen, O., Lohse, K. R., & Carter, M. J. (2022). Increased perceptions of autonomy through choice fail to enhance motor skill retention. *Journal of Experimental Psychology: Human Perception and Performance*, 48(4), 370–379. https://doi.org/10.1037/xhp0000992

### Bibtex

<pre>
@article{,
  title = {Increased Perceptions of Autonomy through Choice Fail to Enhance Motor Skill Retention.},
  author = {St. Germain, Laura and Williams, Allison and Balbaa, Noura and Poskus, Andrew and Leshchyshen, Olena and Lohse, Keith R. and Carter, Michael J.},
  date = {2022-04},
  journaltitle = {Journal of Experimental Psychology: Human Perception and Performance},
  shortjournal = {Journal of Experimental Psychology: Human Perception and Performance},
  volume = {48},
  number = {4},
  pages = {370--379},
  issn = {1939-1277, 0096-1523},
  doi = {10.1037/xhp0000992},
  url = {http://doi.apa.org/getdoi.cfm?doi=10.1037/xhp0000992},
  urldate = {2023-07-13},
  langid = {english}
}
</pre>

## Abstract

There has been growing research interest in the effects that motivation plays in motor learning, and specifically how autonomy, competence, and social relatedness may directly benefit the learning process. Here, we present a preregistered manipulation of autonomy-support by providing learners with choice during the practice of a speed cup-stacking task. One group was given control over when a video demonstration was provided and the viewing speed. A yoked control group received an identical demonstration schedule, but without choice (as their schedule was matched to a participant with choice). Critically, we addressed a gap in the literature by adding a yoked group who was explicitly told that they were being denied choice and that their schedule was chosen by another participant. We found no statistically significant learning differences between groups, despite finding evidence that providing choice increased perceived autonomy. Equivalence tests further showed that although the groups were not statistically equivalent, the effect size is likely too small to practically study the effects of autonomy-support through choice in most motor learning labs. These findings add to a growing body of research that questions a causal role of autonomy-support on motor learning, and the robustness of the so-called self-controlled learning advantage.
