---
title: "The combination of reporting bias and underpowered study designs has substantially exaggerated the motor learning benefits of self-controlled practice and enhanced expectancies: A meta-analysis"
type: "article"
author: "McKay B., Bacelar MFB., Parma JO., Miller MW., & Carter, MJ."
year: "2023"
publication: "International Review of Sport and Exercise Psychology"
pdf: ""
doi: "https://doi.org/10.1080/1750984X.2023.2207255"
github: "https://github.com/cartermaclab/proj_sc-ee-optimal-theory"
materials: "https://osf.io/vfza7/"
#supplementary: ""
preprint: "https://psyarxiv.com/3nhtc/"
toc: false
---

## Citation

### APA 7th

> McKay, B., Bacelar, M. F. B., Parma, J. O., Miller, M. W., & Carter, M. J. (2023). The combination of reporting bias and underpowered study designs has substantially exaggerated the motor learning benefits of self-controlled practice and enhanced expectancies: A meta-analysis. *International Review of Sport and Exercise Psychology*, 0(0), 1–21. https://doi.org/10.1080/1750984X.2023.2207255

### Bibtex

<pre>
@article{,
  title = {The Combination of Reporting Bias and Underpowered Study Designs Has Substantially Exaggerated the Motor Learning Benefits of Self-Controlled Practice and Enhanced Expectancies: {{A}} Meta-Analysis},
  shorttitle = {The Combination of Reporting Bias and Underpowered Study Designs Has Substantially Exaggerated the Motor Learning Benefits of Self-Controlled Practice and Enhanced Expectancies},
  author = {McKay, Brad and Bacelar, Mariane F. B. and Parma, Juliana O. and Miller, Matthew W. and Carter, Michael J.},
  date = {2023-05-04},
  journaltitle = {International Review of Sport and Exercise Psychology},
  volume = {0},
  number = {0},
  pages = {1--21},
  publisher = {{Routledge}},
  issn = {1750-984X},
  doi = {10.1080/1750984X.2023.2207255},
  url = {https://doi.org/10.1080/1750984X.2023.2207255},
  urldate = {2023-07-13},
  keywords = {motivation,OPTIMAL theory,publication bias,roBMA,Z-curve}
}
</pre>

## Abstract

Enhanced expectancies and autonomy-support through self-controlled practice conditions form the motivation pillar of OPTIMAL theory [Wulf, G., & Lewthwaite, R. (2016). Optimizing performance through intrinsic motivation and attention for learning: The OPTIMAL theory of motor learning. *Psychonomic Bulletin & Review*, 23(5), 1382–1414. https://doi.org/10.3758/s13423-015-0999-9]. The influence of these practice variables on motor learning was recently evaluated in two separate meta-analyses. Both meta-analyses found that the published literature suggested a moderate and significant benefit on motor learning; however, evidence for reporting bias was found in both literatures. Although multiple bias-corrected estimates were reported in the self-controlled meta-analysis, there was no principled way to prefer one over the other. In the enhanced expectancies meta-analysis, the trim-and-fill-technique failed to correct the estimated effects. Here, we addressed these limitations by reanalyzing the data from both meta-analyses using robust Bayesian meta-analysis methods. Our reanalysis revealed that reporting bias substantially exaggerated the benefits of these practice variables in the original meta-analyses. The true effects appear small, uncertain, and potentially null. We found the estimated average statistical power among all studies from the original meta-analyses was 6% (95% confidence interval [5%, 13%]). These results provide compelling and converging evidence that strongly suggests the available literature is insufficient to support the motivation pillar of OPTIMAL theory. Our results highlight the need for adequately powered experimental designs if motor learning scientists want to make evidence-based recommendations.
