---
title: "On the reproducibility of power analyses in motor behavior research"
type: "article"
author: "McKay B., Bacelar MFB., & Carter MJ."
year: "2023"
publication: "Journal of Motor Learning and Development"
pdf: ""
doi: "https://doi.org/10.1123/jmld.2022-0061"
github: "https://github.com/cartermaclab/proj_power-reproducibility-motor-behaviour"
materials: "https://osf.io/9a6m8/"
#supplementary: ""
preprint: "https://doi.org/10.51224/SRXIV.184"
toc: false
---

## Citation

### APA 7th

> McKay, B., Bacelar, M. F. B., & Carter, M. J. (2023). On the reproducibility of power analyses in motor behavior research. *Journal of Motor Learning and Development*, 11(1), 29–44. https://doi.org/10.1123/jmld.2022-0061

### Bibtex

<pre>
@article{,
  title = {On the Reproducibility of Power Analyses in Motor Behavior Research},
  author = {McKay, Brad and Bacelar, Mariane F. B. and Carter, Michael J.},
  date = {2023-03-03},
  journaltitle = {Journal of Motor Learning and Development},
  volume = {11},
  number = {1},
  pages = {29--44},
  publisher = {{Human Kinetics}},
  issn = {2325-3193, 2325-3215},
  doi = {10.1123/jmld.2022-0061},
  url = {https://journals.humankinetics.com/view/journals/jmld/11/1/article-p29.xml},
  urldate = {2023-07-13},
  langid = {english}
}
</pre>

## Abstract

Recent metascience suggests that motor behavior research may be underpowered, on average. Researchers can perform a priori power analyses to ensure adequately powered studies. However, there are common pitfalls that can result in underestimating the required sample size for a given design and effect size of interest. Critical evaluation of power analyses requires successful analysis reproduction, which is conditional on the reporting of sufficient information. Here, we attempted to reproduce every power analysis reported in articles (*k* = 84/635) in three motor behavior journals between January 2019 and June 2021. We reproduced 7% of analyses using the reported information, which increased to 43% when we assumed plausible values for missing parameters. Among studies that reported sufficient information to evaluate, 63% reported using the same statistical test in the power analysis as in the study itself, and in 77%, the test addressed at least one of the identified hypotheses. Overall, power analyses were not commonly reported with sufficient information to ensure reproducibility. A nontrivial number of power analyses were also affected by common pitfalls. There is substantial opportunity to address the issue of underpowered research in motor behavior by increasing adoption of power analyses and ensuring reproducible reporting practices.
