---
title: "Visual accuracy dominates over haptic speed for state estimation of a partner during collaborative sensorimotor interactions"
type: "article"
author: "Lokesh R., Sullivan SR., St. Germain L., Roth AM., Calalo JA., Buggeln J., Ngo T., Marchhart VRF., Carter MJ., & Cashaback JGA."
year: "2023"
publication: "Journal of Neurophysiology"
pdf: ""
doi: "https://doi.org/10.1152/jn.00053.2023"
github: ""
materials: ""
#supplementary: "https://doi.org/10.6084/m9.figshare.22704598"
preprint: ""
toc: false
---

## Citation

### APA 7th

> Lokesh, R., Sullivan, S. R., St. Germain, L., Roth, A. M., Calalo, J. A., Buggeln, J., Ngo, T., Marchhart, V. R. F., Carter, M. J., & Cashaback, J. G. A. (2023). Visual accuracy dominates over haptic speed for state estimation of a partner during collaborative sensorimotor interactions. *Journal of Neurophysiology*, 130(1), 23–42. https://doi.org/10.1152/jn.00053.2023

### Bibtex

<pre>
@article{,
  title = {Visual Accuracy Dominates over Haptic Speed for State Estimation of a Partner during Collaborative Sensorimotor Interactions},
  author = {Lokesh, Rakshith and Sullivan, Seth R. and St. Germain, Laura and Roth, Adam M. and Calalo, Jan A. and Buggeln, John and Ngo, Truc and Marchhart, Vanessa R. F. and Carter, Michael J. and Cashaback, Joshua G. A.},
  date = {2023-07},
  journaltitle = {Journal of Neurophysiology},
  volume = {130},
  number = {1},
  pages = {23--42},
  publisher = {{American Physiological Society}},
  issn = {0022-3077},
  doi = {10.1152/jn.00053.2023},
  url = {https://journals.physiology.org/doi/full/10.1152/jn.00053.2023},
  urldate = {2023-07-13},
  keywords = {collaboration,human-human interaction,optimal feedback control,sensorimotor,uncontrolled manifold}
}
</pre>

## Abstract

We routinely have physical interactions with others, whether it be handing someone a glass of water or jointly moving a heavy object together. These sensorimotor interactions between humans typically rely on visual feedback and haptic feedback. Recent single-participant studies have highlighted that the unique noise and time delays of each sense must be considered to estimate the state, such as the position and velocity, of one’s own movement. However, we know little about how visual feedback and haptic feedback are used to estimate the state of another person. Here, we tested how humans utilize visual feedback and haptic feedback to estimate the state of their partner during a collaborative sensorimotor task. Across two experiments, we show that visual feedback dominated haptic feedback during collaboration. Specifically, we found that visual feedback led to comparatively lower task-relevant movement variability, smoother collaborative movements, and faster trial completion times. We also developed an optimal feedback controller that considered the noise and time delays of both visual feedback and haptic feedback to estimate the state of a partner. This model was able to capture both lower task-relevant movement variability and smoother collaborative movements. Taken together, our empirical and modeling results support the idea that visual accuracy is more important than haptic speed to perform state estimation of a partner during collaboration.
