---
title: "Decreasing the proportion of self-control trials during the acquisition period does not compromise the learning advantages in a self-controlled context"
type: "article"
author: "Patterson JT., Carter MJ., & Sanli E."
year: "2011"
publication: "Research Quarterly for Exercise and Sport"
pdf: ""
doi: "https://doi.org/10.1080/02701367.2011.10599799"
github: ""
materials: ""
#supplementary: ""
preprint: ""
toc: false
---

## Citation

### APA 7th

> Patterson, J. T., Carter, M. J., & Sanli, E. (2011). Decreasing the proportion of self-control trials during the acquisition period does not compromise the learning advantages in a self-controlled context. *Research Quarterly for Exercise and Sport*, 82(4), 624–633. https://doi.org/10.1080/02701367.2011.10599799

### Bibtex

<pre>
@article{,
  title = {Decreasing the Proportion of Self-Control Trials during the Acquisition Period Does Not Compromise the Learning Advantages in a Self-Controlled Context},
  author = {Patterson, Jae T. and Carter, Michael J. and Sanli, Elizabeth},
  date = {2011-12-01},
  journaltitle = {Research Quarterly for Exercise and Sport},
  volume = {82},
  number = {4},
  eprint = {22276404},
  eprinttype = {pmid},
  pages = {624--633},
  publisher = {{Routledge}},
  issn = {0270-1367},
  doi = {10.1080/02701367.2011.10599799},
  url = {https://doi.org/10.1080/02701367.2011.10599799},
  urldate = {2023-07-13},
  keywords = {knowledge of results,perceptuomotor processes,sequence learning}
}
</pre>

## Abstract

The present experiment examined the learning effects of participants self-controlling their receipt of knowledge of results (KR) on all or half of their acquisition trials (50%). For participants who were provided 50% self-control, the first half of their acquisition period consisted of receiving KR on all trials, or according to a faded-KR schedule. Participants practiced a sequential timing task. The results showed that independent of practice condition, participants who self-controlled their KR during the acquisition period demonstrated superior performance compared to the respective yoked conditions in the retention and transfer portion of the experiment. These results extend previous research by suggesting that decreasing the proportion of self-control trials does not compromise learning in a self-controlled context.
