---
title: "Self-controlled knowledge of results: Age-related differences in motor learning, strategies, and error detection"
type: "article"
author: "Carter MJ. & Patterson JT."
year: "2012"
publication: "Human Movement Science"
pdf: ""
doi: "https://doi.org/10.1016/j.humov.2012.07.008"
github: ""
materials: ""
#supplementary: ""
preprint: ""
toc: false
---

## Citation

### APA 7th

> Carter, M. J., & Patterson, J. T. (2012). Self-controlled knowledge of results: Age-related differences in motor learning, strategies, and error detection. *Human Movement Science*, 31(6), 1459–1472. https://doi.org/10.1016/j.humov.2012.07.008

### Bibtex

<pre>
@article{,
  title = {Self-Controlled Knowledge of Results: {{Age-related}} Differences in Motor Learning, Strategies, and Error Detection},
  shorttitle = {Self-Controlled Knowledge of Results},
  author = {Carter, Michael J. and Patterson, Jae T.},
  date = {2012-12-01},
  journaltitle = {Human Movement Science},
  shortjournal = {Human Movement Science},
  volume = {31},
  number = {6},
  pages = {1459--1472},
  issn = {0167-9457},
  doi = {10.1016/j.humov.2012.07.008},
  url = {https://www.sciencedirect.com/science/article/pii/S0167945712001017},
  urldate = {2023-07-13},
  langid = {english},
  keywords = {Error detection,Feedback,Older adults,Performance estimation,Practice}
}
</pre>

## Abstract

Research has demonstrated that a self-controlled KR schedule is advantageous for motor learning; however, the usefulness of a self-controlled KR context in older adults remains unknown. To address this gap in knowledge, we examined whether (1) the learning benefits of a self-controlled KR schedule are modulated by the age of the learner; (2) practicing in a self-controlled KR context concurrently strengthens the learner’s error detection mechanism, and (3) the KR strategy during acquisition changes as a function of practice trials completed and age. As a function of age, participants were quasirandomly assigned to either the self-control or yoked group resulting in four experimental groups (Self-Young, Yoked-Young, Self-Old, and Yoked-Old). The results revealed the Self-Young group: (1) demonstrated superior retention performance than all other groups (*p* < .05); (2) was more accurate in estimating motor performance than all other groups during retention (*p* < .05), and (3) self-reported a switch in their strategy for requesting KR during acquisition based on the number of practice trials completed. Collectively, our findings suggest that older adults do not demonstrate the same learning benefits of a self-controlled KR context as younger adults which may be attributed to differences in KR strategies.
