---
title: "Self-controlled KR schedules: Does repetition order matter?"
type: "article"
author: "Patterson JT., Carter MJ., & Hansen S."
year: "2013"
publication: "Human Movement Science"
pdf: ""
doi: "https://doi.org/10.1016/j.humov.2013.03.005"
github: ""
materials: ""
#supplementary: ""
preprint: ""
toc: false
---

## Citation

### APA 7th

> Patterson, J. T., Carter, M. J., & Hansen, S. (2013). Self-controlled KR schedules: Does repetition order matter? *Human Movement Science*, 32(4), 567–579. https://doi.org/10.1016/j.humov.2013.03.005

### Bibtex

<pre>
@article{,
  title = {Self-Controlled {{KR}} Schedules: {{Does}} Repetition Order Matter?},
  shorttitle = {Self-Controlled {{KR}} Schedules},
  author = {Patterson, Jae T. and Carter, Michael J. and Hansen, Steve},
  date = {2013-08-01},
  journaltitle = {Human Movement Science},
  shortjournal = {Human Movement Science},
  volume = {32},
  number = {4},
  pages = {567--579},
  issn = {0167-9457},
  doi = {10.1016/j.humov.2013.03.005},
  url = {https://www.sciencedirect.com/science/article/pii/S0167945713000456},
  urldate = {2023-07-13},
  langid = {english},
  keywords = {2330,2340,2343,Feedback,Knowledge of results,Learning,Practice schedule,Self-control}
}
</pre>

## Abstract

The impact of an experimenter-defined repetition schedule on the utility of a self-controlled KR context during motor skill acquisition was examined. Participants were required to learn three novel spatial-temporal tasks in either a random or blocked repetition schedule with or without the opportunity to control their KR. Results from the retention period showed that participants provided control over their KR schedule in a random repetition schedule demonstrated superior learning. However, performance measures from the transfer test showed that, independent of repetition schedule, learners provided the opportunity to control their KR schedule demonstrated superior transfer performance compared to their yoked counterparts. The dissociated impact of repetition schedule and self-controlled KR schedules on retention and transfer is discussed.
